export const contactList = [
    {
      id: 1,
      name: "Maya Kasuma",
      profilePic: "https://www.whatsappimages.in/wp-content/uploads/2022/05/dp-for-girls-attitude.jpg",
      lastText: "Hey Man",
      lastTextTime: "3:48 PM",
    },
    {
      id: 2,
      name: "Steve Ballmer",
      profilePic: "https://i.pinimg.com/originals/18/ea/0a/18ea0a314a497ff12f62bb1152f83b38.jpg",
      lastText: `I'm with @theindiandev`,
      lastTextTime: "2:45 PM",
    },
    {
      id: 3,
      name: "Stasa Benko",
      profilePic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCTOJACRy_kQ9DA-f-HWRBcK0Pwi615z1pxt9QxGmEvhpXOddC9QKPW5-U6YYpqiGPcLU&usqp=CAU",
      lastText: "Where is my Tesla?",
      lastTextTime: "10:04 PM",
    },
    {
      id: 4,
      name: "Alice Whitman",
      profilePic: "https://img.freepik.com/free-photo/close-up-portrait-wonderful-child-with-shiny-brown-eyes-looking-with-interest-enthusiastic-little-girl-vintage-straw-hat-decorated-with-ribbon-posing-during-game-park_197531-3960.jpg?w=2000",
      lastText: "Travelling to space",
      lastTextTime: "8:32 PM",
    },
    {
      id: 5,
      name: "Clippy",
      profilePic: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bWFuJTIwcG9ydHJhaXR8ZW58MHx8MHx8&w=1000&q=80",
      lastText: "Travelling to space",
      lastTextTime: "12:32 PM",
    },
    {
      id: 6,
      name: "Henry Strachan",
      profilePic: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
      lastText: "Travelling to space",
      lastTextTime: "05/11",
    },
    {
      id: 7,
      name: "Jihoon Seo",
      profilePic: "https://www.whatsappimages.in/wp-content/uploads/2022/02/girls-dp-Wallpaper-scaled.jpg",
      lastText: "Travelling to space",
      lastTextTime: "05/11",
    },
  ];
  export const messagesList = [
    {
      id: 1,
      messageType: "TEXT",
      text: "Hey Man 😁",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 2,
      messageType: "TEXT",
      text: "Hey, What's up?",
      senderID: 1,
      addedOn: "12:01 PM",
    },
    {
      id: 3,
      messageType: "TEXT",
      text: "All Good, What about you?",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 4,
      messageType: "TEXT",
      text: "I'm good as well",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 5,
      messageType: "TEXT",
      text: "Great 😁",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 5,
      messageType: "TEXT",
      text: "Have you subscribed The Indian Dev ?",
      senderID: 1,
      addedOn: "12:00 PM",
    },
  ];